### ISSUE TITLE
Estimating time and effort for new user requirments

### ISSUE THREAD

**Issue by amyburness** [kartoza/cplus-plugin#215]
Please estimate the required time and effort to implement the following requirements for the plugin

- a dialogue where the carbon layers can be assigned to each NCS pathway (averaged if more then one carbon layer applies to each pathway) and an overall importantness coefficient assigned to the carbon between 1-5 (already in the plugin) 
- need to allow the multiplication of the carbon and NCS suitability coefficients
- Need to add a place to define the coefficient into the settings dialogue and add the coefficient into the calculation in the processing engine
- Need the time to  implement change or update the aster calculator

**Comment by amyburness** [comment]
@Samweli This morning ended up being a bit hectic. For estimation please can you have a look at estimating how much effort for the following let me know if I have left anything out that you see in the big picture model and from our conversations. 

New UR's 
Adding the field for the NCS suitability coefficient into the settings panel
Adding a dialogue where users can assign the carbon layers to the specific NCS pathways (sometimes more then 1 carbon layer applies to the NCS) I see this happening similarly to step 2 or 3 (perhaps we could make a new step in the process for carbon layers assigning before the IM creation step) 
Adding the suitability coefficient to the NCS pathway calculation eg ((suitability coefficient (value between 0-5)) * (NSC pathway) + (carbon coefficient(value between 0-5) * (carbon layer (or if more then 1 carbon layer applies then the average of the two))
Adding in the new Normalisation step for the NCS pathways that includes the multiplication of the carbon and suitability coefficients

Things that we need to do to get the processing engine working as envisioned for epic 2
make all weighting values to be between 0-5 (I think this is done).
add a constant zero raster into the first position of the highest point analysis to filter out the zero valued NULLS.
I think we retain the raster calculator throughout as plugging the nulls with zeros fixes the data loss problem.
incorporate the snap-raster functionality Nyll mentioned we can add.

Note: with the zero plugging we don't really need to update the raster calculator at all but it would be nice for greater good.

**Comment by Samweli** [comment]
Submitted new tickets for implementation of the new functionality https://github.com/kartoza/cplus-plugin/issues/228, https://github.com/kartoza/cplus-plugin/issues/232, https://github.com/kartoza/cplus-plugin/issues/236, https://github.com/kartoza/cplus-plugin/issues/240
