### ISSUE TITLE
Normalize pathways before creating implementation models

### ISSUE THREAD

**Issue by Samweli** [kartoza/cplus-plugin#232]
Add a new step in the analysis processing after weighting the pathways to normalize the pathways. This will make the resulting pathways values to range from 0 to 1.

Use the raster calculator for the normalization calculation and the QGIS API to fetch the minimum and maximum value for the pathways bands. The calculation for normalization is
 `(pathway layer - minimum band value) / (maximum band value - minimum band value)`
 
The normalization implementation should contain its own plugin function that is testable and run on a separate thread, use the [QgsTask API](https://qgis.org/pyqgis/3.0/core/Task/QgsTask.html) to achieve this, this new step should follow the already established workflow for the plugin processing as outlined from the plugin API [here](https://kartoza.github.io/cplus-plugin/developer/api/gui/api_gui_main/#__codelineno-0-577)

**Comment by amyburness** [comment]
we need to multiply the normalization by the sum of the coefficients chosen by the user for the Suitability coefficient (1-5) the Carbon coefficient (0-5)
```(pathway layer - minimum band value) / (maximum band value - minimum band value) *(suitability coefficient value + carbon coefficient value) ```
