### ISSUE TITLE
[User Documentation] Highest position analysis change

### ISSUE THREAD

**Issue by Samweli** [kartoza/cplus-plugin#239]
Based on https://github.com/kartoza/cplus-plugin/issues/236

Update the plugin user documentation to show how the highest position analysis is incorporated in the plugin among other processing steps. When necessary provide highlights from the new QGIS model for the scenario analysis.

Users should be able to find the new documentation updates in https://kartoza.github.io/cplus-plugin/user/

**Comment by vermeulendivan** [comment]
Add screenshots to QGIS logs which refers to the Equations being executed

**Comment by Samweli** [comment]
Closed the original ticket https://github.com/kartoza/cplus-plugin/issues/236
