### ISSUE TITLE
Translate Current model into QGIS Modeler

### ISSUE THREAD

**Issue by amyburness** [kartoza/cplus-plugin#34]
Take the current model Created by @davhunt710 and translate it to QGIS as the basis of the plugin. 

ArcMap model:
![image](https://user-images.githubusercontent.com/79740955/231807019-dc98ad06-2f62-45ae-9266-4b7c9cae99e2.png)

**Comment by vermeulendivan** [comment]
@Samweli @amyburness 
ArcMap model has been translated into the QGIS model builder.
The steps IsNull -> Con in the ArcMap model can be done with the Fill nodata cells tool in QGIS.

![QGIS_model](https://user-images.githubusercontent.com/79740955/234513252-64ccdf04-62c6-4889-b069-52c802996cf9.png)

**Comment by vermeulendivan** [comment]
The model has been further updated. The filling of nodata cells are no longer required as the Highest position in stack tool in QGIS has an option to ignore nodata values. This is not the case Arcmap, and is why it were required. This means that the model is "smaller" in QGIS.

![QGIS_model](https://user-images.githubusercontent.com/79740955/236816257-0ac2c4bf-fa77-4bba-af4b-56a861c62019.png)

**Comment by vermeulendivan** [comment]
@Samweli This should also be closed
