### ISSUE TITLE
Create plugin configuration tab in the QGIS options

### ISSUE THREAD

**Issue by amyburness** [kartoza/cplus-plugin#35]
Analysis config:
- Organization
- Contact email
- Website
- Custom logo
- Logo preview
- Licence

Download:
- Data location: Location in which default data is stored
- Download data: Open above location?

![image](https://user-images.githubusercontent.com/77841514/231751115-571b0b44-77f1-4848-a9e9-ab81a818e5ba.png)

**Comment by vermeulendivan** [comment]
Are these analysis config options optional?
Should a user always provide a default location before using the plugin?

**Comment by vermeulendivan** [comment]
@Samweli This is a duplicate of the options, can be closed
