### ISSUE TITLE
Create Plugin Main Dialogue

### ISSUE THREAD

**Issue by amyburness** [kartoza/cplus-plugin#36]
The dialogue should allow the user to:
- name the scenario
- scenario description
- area of interest (with default QGIS widget)
![image](https://user-images.githubusercontent.com/77841514/231751805-5e62cda6-2d14-4f52-ae28-64b46c5908f3.png)

**Comment by vermeulendivan** [comment]
Should the default extent be that of the layer?
Should it be masked?
