### ISSUE TITLE
Create a tab for assigning NCS pathways to create implementation models

### ISSUE THREAD

**Issue by amyburness** [kartoza/cplus-plugin#37]
Create a tab from which the user can 
- list of available pathways/implementation models
- implementation models should be grouped
- click and drag ncs pathways to assign them to create different implementation models
- field to view and add descriptions for both pathways and models
- add an implementation model name
- add pathway layers to pathway list to be able to use to assign
- editing option for pathways and implementation models
- the user should not be allows to continue to the next step/tab if this step is not completed

![image](https://user-images.githubusercontent.com/77841514/231754444-d18e5073-458a-4c23-8b24-8981acb1f430.png)

**Comment by vermeulendivan** [comment]
Might be better to add only on Description box which will show the description for both pathways and implementation models. Basically the last element clicked in one of the lists.
Less clutter in the UI and more space to show the description.
