### ISSUE TITLE
Plugin documentation

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/cplus-plugin#45]
Document the features of the plugin and the work which went into the development of the plugin. Provide a proper explanation of the plugin workflow.

- Workflow (QGIS model created from the ArcPy model)
- Functionality of the plugin
- Encountered problems and workarounds
- Changes to the original scope
- etc

**Comment by Samweli** [comment]
Duplicate of https://github.com/kartoza/cplus-plugin/issues/50
