### ISSUE TITLE
Continuous Integration (CI) automated build and testing

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/cplus-plugin#47]
The setup should enable running tests against QGIS LTR, QGIS nightly and QGIS 3.22 versions. See https://github.com/qgis/QGIS/tree/master/.docker/qgis_resources/test_runner for reference in running plugin test inside QGIS application

**Comment by Samweli** [comment]
Complete in https://github.com/kartoza/cplus-plugin/commit/0aa9cea99561d1ab487018108dc2c24c1f6ea08e
