### ISSUE TITLE
Design documentation site

### ISSUE THREAD

**Issue by Samweli** [kartoza/cplus-plugin#50]
The plugin will have a site for documentation, that will be updated per plugin release.
The documentation site will be created using the [GitHub Pages ](https://pages.github.com/) feature and the [ mkdocs tools ](https://squidfunk.github.io/mkdocs-material/) in order to automate the content generation from plugin release and deployments.

The site theme is to be decided by the developer choosen design, it should also cover the plugin project background, development section, plugin API and Usage, tutorial sections and plugin features.

**Comment by vermeulendivan** [comment]
Nice video on how to get started with mkdocs: https://www.youtube.com/watch?v=Q-YA_dA8C20

**Comment by vermeulendivan** [comment]
- After mk docs has been added to the repo, go to settings
 - Click on Pages
 - Set the branch to gh-pages
 - Click Save
 - Click on the Actions tab
 - Select the action
 - Select Deploy
 - Open Run mkdocs gh-deploy
 - URL can be found there

**Comment by vermeulendivan** [comment]
Just an example if someone wants to have a look. Did start putting mk-docs together for cplus.
https://github.com/vermeulendivan/mk-docs-tut
